// CENTRALIZED DICTIONARY DATA
const dictionaryData = [
    // --- TACTICAL ANS GAMEPLAY ---
    { term: "Aguas", literal: "Waters.", meaning: "Watch out! / Careful!", category: "Tactical", context: "Warning when you see an enemy or hear footsteps.", quote: "¡Aguas, wey! Estan campeando ahi adentro.", audio: "audio/aguas.m4a" },
    { term: "Amontonados", literal: "Piled up.", meaning: "Stacked / Grouped up (enemies).", category: "Tactical", context: "Enemy team is bunched together.", quote: "¡Están todos amontonados en esa casa, aguas!", audio: "audio/amontonados.m4a" },
    { term: "Al tiro", literal: "At the shot.", meaning: "On point / Ready / Attentive.", category: "Tactical", context: "Focused or alert.", quote: "Ponte al tiro, ahi vienen wey.", audio: "audio/altiro.m4a" },
    { term: "A pata", literal: "On foot.", meaning: "Walking / On foot.", category: "Tactical", context: "No vehicle, caught outside zone.", quote: "Nos toca irnos a pata hasta la zona.", audio: "audio/apata.m4a" },
    { term: "En corto", literal: "In short.", meaning: "Right away / Quickly.", category: "Tactical", context: "Need something done immediately.", quote: "Revíveme en corto, wey.", audio: "audio/encorto.m4a" },
    { term: "En caliente", literal: "In hot.", meaning: "Right now / Fast.", category: "Tactical", context: "Maximum speed.", quote: "Cáele en caliente a la tienda.", audio: "audio/encaliente.m4a" },
    { term: "Fierro", literal: "Iron / Tool.", meaning: "Let's go / Bet / Done deal.", category: "Tactical", context: "Enthusiasm, agreeing to a plan, or hype.", quote: "¡Fierro fierro, hay que ganar!", audio: "audio/fierro.m4a" },
    { term: "Tirar paro", literal: "To throw a stop.", meaning: "To do a favor or to help.", category: "Tactical", context: "Need a revive or ammo.", quote: "Tirame paro con una placa, wey.", audio: "audio/tirarrparo.m4a" },
    { term: "Echarse una mano", literal: "To throw a hand.", meaning: "To help out / To assist.", category: "Tactical", context: "Friendly backup request.", quote: "Amara, échame una mano con estos sin chambas.", audio: "audio/echarsemano.m4a" },

    // --- INSULTS AND ROASTS ---
    { term: "Hocicon", literal: "Big snout.", meaning: "Loudmouth, trash talker.", category: "Insults", context: "Talking shit but can't back it up.", quote: "Tan hocicon y no la armas, a chingar a su madre pa la lobby.", audio: "audio/hocicon.m4a" },
    { term: "Mamón", literal: "Sucker.", meaning: "Arrogant, jerk, trying too hard.", category: "Insults", context: "Sweaty lobby/player.", quote: "Ay, qué mamón eres.", audio: "audio/mamon.m4a" },
    { term: "Puñetas", literal: "Wanks.", meaning: "Complete idiot / Useless.", category: "Insults", context: "Doing something stupid.", quote: "Estas bien puñetas wey.", audio: "audio/punetas.m4a" },
    { term: "Chamaco Miado", literal: "Piss covered kid.", meaning: "Brat / Squeaker.", category: "Insults", context: "Immature child/behavior.", quote: "Ya cállese, pinche chamaco miado.", audio: "audio/chamaco.m4a" },
    { term: "Hambreado", literal: "Starving.", meaning: "Extremely thirsty for a kill.", category: "Insults", context: "Desperate chasing.", quote: "No seas tan hambreado wey.", audio: "audio/hambreado.m4a" },
    { term: "Llorón", literal: "Crier.", meaning: "Crybaby / Complainer.", category: "Insults", context: "Complaining about aim assist/hacks.", quote: "No seas llorón.", audio: "audio/lloron.m4a" },
    { term: "Espantaviejas", literal: "Woman scarer.", meaning: "Incel / Tryhard.", category: "Insults", context: "Acting weird when hearing a girl.", quote: "Mi compa el espantaviejas.", audio: "audio/espantaviejas.m4a" },
    { term: "Culón", literal: "Big ass.", meaning: "Coward / Pussy.", category: "Insults", context: "Talking big then running.", quote: "Pa que corres, no seas culon.", audio: "audio/culon.m4a" },
    { term: "Codo", literal: "Elbow.", meaning: "Cheap / Stingy.", category: "Insults", context: "Won't buy/share loot.", quote: "No seas codo, suelta el dinero.", audio: "audio/codo.m4a" },
    { term: "Fresa", literal: "Strawberry.", meaning: "Preppy / Stuck up.", category: "Insults", context: "Acting posh.", quote: "No seas fresa wey.", audio: "audio/fresa.m4a" },
    { term: "Maleta", literal: "Suitcase.", meaning: "Bad at the game.", category: "Insults", context: "Playing terribly.", quote: "Estás bien maleta wey, mejor desinstala esta madre.", audio: "audio/maleta.m4a" },
    { term: "Baboso", literal: "Drooling.", meaning: "Dumbass / Moron.", category: "Insults", context: "Silly mistake.", quote: "No seas baboso, ¿cómo te vas a morir así wey?", audio: "audio/baboso.m4a" },
    { term: "Ojete", literal: "Asshole.", meaning: "Mean person / Jerk.", category: "Insults", context: "Acting malicious.", quote: "No seas ojete, revíveme.", audio: "audio/ojete.m4a" },
    { term: "Metiche", literal: "Meddlesome.", meaning: "Busybody / Nosy.", category: "Insults", context: "Interfering.", quote: "No seas metiche.", audio: "audio/metiche.m4a" },
    { term: "Culero", literal: "Ass related.", meaning: "Asshole / Jerk / Cowardly.", category: "Insults", context: "Cheating/mean.", quote: "No seas culero y suéltame la feria.", audio: "audio/culero.m4a" },
    { term: "Sin chamba", literal: "Without a job.", meaning: "No-lifer / Tryhard / Sweat.", category: "Insults", context: "Camping/sweaty.", quote: "Pinches sin chamba.", audio: "audio/sinchamba.m4a" },
    { term: "Pégate un baño", literal: "Go take a bath.", meaning: "Touch grass / Get a life.", category: "Insults", context: "Sweaty player.", quote: "Relájate y pégate un baño, nomas son pubs", audio: "audio/pegateunbano.m4a" },
    { term: "Rarito", literal: "A little weird.", meaning: "Strange / Sketchy.", category: "Insults", context: "Acting suspicious.", quote: "Ese vato se mueve bien rarito, ¿Esta hackeando?", audio: "audio/rarito.m4a" },
    { term: "Me la pelas", literal: "You peel it for me.", meaning: "You can't touch me.", category: "Vibe", context: "Outgunning a tryhard.", quote: "Me la pelaste wey.", audio: "audio/melapelas.m4a" },

    // --- VIBE, SOCIAL AND REACTIONS ---
    { term: "Agüitado", literal: "To get watery.", meaning: "Feeling down / Bummed out.", category: "Vibe", context: "Defeated/Low motivation.", quote: "Ando bien agüitada. OR No te agüites, wey.", audio: "audio/aguitado.m4a" },
    { term: "Curada", literal: "Cured.", meaning: "Cool, funny, or awesome.", category: "Vibe", context: "Funny clip/chat.", quote: "Qué curada está ese clip.", audio: "audio/curada.m4a" },
    { term: "Arre", literal: "Giddy-up.", meaning: "Say less / Bet.", category: "Vibe", context: "Agreeing to run something.", quote: "Arre arre, ¿cual?.", audio: "audio/arre.m4a" },
    { term: "Cámara", literal: "Camera.", meaning: "Alright / Got it.", category: "Vibe", context: "Confirmation.", quote: "—¿Compramos loady? —¡Cámara!", audio: "audio/camara.m4a" },
    { term: "Chingón", literal: "Badass / Cool.", meaning: "Awesome / High quality.", category: "Vibe", context: "Goated play.", quote: "¡Pinche tiro tan chingón te aventaste!", audio: "audio/chingon.m4a" },
    { term: "Ni modo", literal: "No way.", meaning: "Oh well / It is what it is.", category: "Vibe", context: "Stupid death.", quote: "Nos mataron we... ni modo.", audio: "audio/nimodo.m4a" },
    { term: "Qué onda", literal: "What wave.", meaning: "What's up?", category: "Vibe", context: "Greeting.", quote: "¿Qué onda contigo Amara?", audio: "audio/queonda.m4a" },
    { term: "No mames", literal: "Don't suck.", meaning: "No way / You're kidding.", category: "Vibe", context: "Shock/Disaster.", quote: "¡No mames, como me mata ese pinche bot!", audio: "audio/nomames.m4a" },
    { term: "Wey", literal: "Ox.", meaning: "Bro / Man.", category: "Vibe", context: "Addressing friends.", quote: "¿Qué haces, wey?", audio: "audio/wey.m4a" },
    { term: "Vale madre", literal: "It is worth a mother.", meaning: "Doesn't matter / Who cares.", category: "Vibe", context: "Giving up/Fed up.", quote: "Ya valió madre esta partida.", audio: "audio/valemadre.m4a" },
    { term: "A toda madre", literal: "At all mother.", meaning: "Really cool / Awesome.", category: "Vibe", context: "Top tier.", quote: "Tu skin está a toda madre.", audio: "audio/atodamadre.m4a" },
    { term: "Chamba", literal: "Job / Work.", meaning: "The grind.", category: "Vibe", context: "Ranking up/farming.", quote: "Me toca hacer toda la chamba en este pinche equipo.", audio: "audio/chamba.m4a" },
    { term: "Gacho", literal: "Ugly / Bad.", meaning: "Bad / Mean / Unpleasant.", category: "Vibe", context: "Unfair situation.", quote: "Nombre se portaron bien gacho conmigo.", audio: "audio/gacho.m4a" },
    { term: "Neta", literal: "Truth.", meaning: "For real.", category: "Vibe", context: "Confirming truth.", quote: "¿Es neta?", audio: "audio/neta.m4a" },
    { term: "Desmadre", literal: "Unmothered.", meaning: "Chaos / Mess.", category: "Vibe", context: "Out of control.", quote: "Habia un desmadre en control.", audio: "audio/desmadre.m4a" },
    { term: "Chido", literal: "Cool / Nice.", meaning: "Cool / Awesome.", category: "Vibe", context: "Something good.", quote: "Tu arma está bien chida.", audio: "audio/chido.m4a" },
    { term: "Cagarla", literal: "To shit it.", meaning: "To mess up.", category: "Vibe", context: "Massive mistake.", quote: "La cagué, me morí a lo pendejo.", audio: "audio/cagarla.m4a" },
    { term: "A huevo", literal: "By egg.", meaning: "Hell yeah / Definitely.", category: "Vibe", context: "Excitement/Agreement.", quote: "¡A huevoooo, ganamos la partida!", audio: "audio/ahuevo.m4a" },
    { term: "Plebe / Plebes", literal: "Child.", meaning: "Kid(s) / Homie(s).", category: "Vibe", context: "Squad/teammates.", quote: "¡Qué rolo, plebes!", audio: "audio/plebe.m4a" },
    { term: "Ingasumadre", literal: "Euphemism.", meaning: "Holy shit / Damn.", category: "Vibe", context: "Sudden shock.", quote: "¡Ingasumadre! De dónde me mato???", audio: "audio/insatumadre.m4a" },
    { term: "Pinche", literal: "Kitchen assistant.", meaning: "Damn / Fucking.", category: "Vibe", context: "Intensifier/Annoyance.", quote: "¡Pinche juego, está lleno de pinches bugs!", audio: "audio/pinche.m4a" },
    { term: "Feria", literal: "Fair.", meaning: "Money / Cash.", category: "Vibe", context: "Loot/cost.", quote: "Ya conseguí la feria para la loady.", audio: "audio/feria.m4a" },
    { term: "Lana", literal: "Wool.", meaning: "Money / Cash.", category: "Vibe", context: "Casual money.", quote: "No tengo nada de lana ahorita, wey.", audio: "audio/lana.m4a" },
    { term: "Naco", literal: "Questionable taste.", meaning: "Tacky / Cringey.", category: "Vibe", context: "Poor taste/style.", quote: "Qué naco te ves con esa skin.", audio: "audio/naco.m4a" },
    { term: "Cáele", literal: "Fall.", meaning: "Come over / Show up.", category: "Vibe", context: "Invite to lobby.", quote: "Cáele a jugar, wey", audio: "audio/caele.m4a" },
    { term: "Chafa", literal: "Low quality.", meaning: "Cheap / Fake.", category: "Vibe", context: "Knock-off/low quality.", quote: "Ese micro se escucha bien chafa, wey.", audio: "audio/chafa.m4a" },
    { term: "Tirar hueva", literal: "Throw laziness.", meaning: "Lazy / Chill.", category: "Vibe", context: "Not playing seriously.", quote: "Hoy no quiero hacer nada, nomas tirar hueva.", audio: "audio/tirarhueva.m4a" },
    { term: "Rífate", literal: "Raffle yourself.", meaning: "Step up / Show off.", category: "Vibe", context: "Hype for a play.", quote: "¡Rífate ese 1v4 Amara!", audio: "audio/rifate.m4a" },
    { term: "Cansado", literal: "Tired.", meaning: "Fed up.", category: "Vibe", context: "Exhausted/bugs.", quote: "Ya estoy cansado de este pinche juego, la neta.", audio: "audio/cansado.m4a" },
    { term: "Vato", literal: "Guy / Dude.", meaning: "Guy, man, or dude.", category: "Vibe", context: "Casual reference.", quote: "Ese vato juega bien, invítalo al equipo.", audio: "audio/vato.m4a" },
    { term: "A todo dar", literal: "At all give.", meaning: "Very good / Awesome.", category: "Vibe", context: "Super cool person.", quote: "Ese vato es a todo dar, deja lo agrego.", audio: "audio/atododar.m4a" },
    { term: "Echarle ganas", literal: "To throw effort.", meaning: "To give it your all.", category: "Vibe", context: "Focus/Work hard.", quote: "¡Échenle ganas, ya casi ganamos plebes!", audio: "audio/echarleganas.m4a" },
    { term: "Maso", literal: "Short for 'más o menos'.", meaning: "So so / Okay.", category: "Vibe", context: "Feeling 'fine'.", quote: "¿Cómo van las partidas Amara? — Ahí, maso.", audio: "audio/maso.m4a" },
    { term: "Cagado", literal: "Shitted.", meaning: "Funny / Hilarious.", category: "Vibe", context: "Funny clip/event.", quote: "Está bien cagado ese clip, wey.", audio: "audio/cagado.m4a" },
    { term: "Ahorita", literal: "Little now.", meaning: "In a little while.", category: "Vibe", context: "Soon (could be hours).", quote: "Ahorita te revivo, espérame.", audio: "audio/ahorita.m4a" },
    { term: "Me vale madre", literal: "Worth a mother.", meaning: "I don't give a fuck.", category: "Vibe", context: "Indifference.", quote: "La neta, me vale madre si perdemos, nomas quiero jugar.", audio: "audio/mevalemadre.m4a" },
    { term: "No te hagas", literal: "Don't make yourself.", meaning: "Don't pretend.", category: "Vibe", context: "Calling out someone.", quote: "No te hagas, si tenias dinero wey", audio: "audio/notehagas.m4a" },
    { term: "Paniquearse", literal: "To panic.", meaning: "Freak out.", category: "Vibe", context: "1v4 pressure.", quote: "No te paniquees, nomas dispara.", audio: "audio/paniquearse.m4a" },
    { term: "No manches", literal: "Don't stain.", meaning: "No way! / You're kidding!", category: "Vibe", context: "Disbelief.", quote: "No manches, ¿cómo me mató ese campero?", audio: "audio/nomanches.m4a" },
    { term: "Emperrarse", literal: "To get like a dog.", meaning: "Get super angry.", category: "Vibe", context: "Losing temper.", quote: "Me emperré machin esa partida.", audio: "audio/emperrarse.m4a" },
    { term: "Chingadera", literal: "Fucking thing.", meaning: "Thing / Junk.", category: "Vibe", context: "Annoying object.", quote: "¡Ya no sirve esta chingadera de monitor!", audio: "audio/chingadera.m4a" },
    { term: "Apendejarse", literal: "To become stupid.", meaning: "Space out / Lose focus.", category: "Vibe", context: "Distracted/Brain dead move.", quote: "La neta me apendejé y me mataron.", audio: "audio/apendejarse.m4a" },
    { term: "Rolón", literal: "Big song.", meaning: "LIL BANGER / Great song.", category: "Vibe", context: "Good track playing.", quote: "Roloooon!", audio: "audio/rolon.m4a" },
    { term: "A la verga (Alv)", literal: "To the...", meaning: "Holy shit / Damn / Fuck off.", category: "Vibe", context: "Surprise/Anger. [EXPLICIT]", quote: "¡ALV! ¿Viste ese snipe?", audio: "audio/alv.m4a" },
    { term: "Ira", literal: "Short for 'mira'.", meaning: "Look.", category: "Vibe", context: "Directing attention.", quote: "Ira, ahí hay uno campeando en la ventana.", audio: "audio/ira.m4a" },
    { term: "Ira nomás", literal: "Look only.", meaning: "Just look at that.", category: "Vibe", context: "Amazement.", quote: "Ira nomás el tiro que se aventó, alv", audio: "audio/iranomas.m4a" }
];